# Generated by Django 3.0.4 on 2020-03-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('p', 'Participation'), ('s', 'Skill')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='degree',
            field=models.CharField(choices=[('D1', 'D1/Ahli Pratama'), ('D2', 'D2/Ahli Muda'), ('D3', 'D3/Ahli Madya'), ('D4', 'D4/Sarjana Sains Terapan'), ('S1', 'S1/Sarjana'), ('S2', 'S2/Magister'), ('S3', 'S3/Doktor')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='domisili',
            field=models.IntegerField(choices=[(0, 'Jabodetabek'), (1, 'Non-Jabodetabek di Pulau Jawa'), (2, 'Luar Pulau Jawa')]),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
    ]
