# Generated by Django 3.0.4 on 2020-03-17 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sceleapp', '0002_auto_20200312_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReplyNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='img',
            new_name='img_loc',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='badge_type',
            new_name='receiving_type',
        ),
        migrations.RenameField(
            model_name='notif',
            old_name='img',
            new_name='img_loc',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='link',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userreply',
            name='course',
        ),
        migrations.AddField(
            model_name='badge',
            name='activity_type',
            field=models.CharField(choices=[('p', 'Create a post'), ('r', 'Create a reply'), ('l', 'Give a like')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='notif',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notif',
            name='user_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserPost'),
        ),
        migrations.AddField(
            model_name='notif',
            name='user_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replylike',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserPost'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user_reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpost',
            name='permalink',
            field=models.CharField(default='dummy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreply',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreply',
            name='permalink',
            field=models.CharField(default='dummy', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='givenpostlike',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='givenreplylike',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notif',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notif',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notif',
            name='notif_type',
            field=models.CharField(choices=[('b', 'Badge'), ('g', 'Grade'), ('l', 'Like'), ('r', 'Reply'), (None, '-------')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='notif',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserPost'),
        ),
        migrations.AlterField(
            model_name='replylike',
            name='user_reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='UserApp',
        ),
        migrations.AddField(
            model_name='replynotif',
            name='notif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sceleapp.Notif'),
        ),
        migrations.AddField(
            model_name='likenotif',
            name='notif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sceleapp.Notif'),
        ),
    ]
