# Generated by Django 3.0.4 on 2020-03-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0003_auto_20200317_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserPost'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='user_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserPost'),
        ),
        migrations.AlterField(
            model_name='replylike',
            name='user_reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserPost'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user_reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
    ]
