# Generated by Django 3.0.4 on 2020-03-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0005_gamification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserPost'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
    ]
