# Generated by Django 3.0.4 on 2020-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0006_auto_20200323_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='code',
            field=models.CharField(default='p1', max_length=3),
            preserve_default=False,
        ),
    ]
