# Generated by Django 3.0.4 on 2020-03-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0007_badge_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
