# Generated by Django 3.0.4 on 2020-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0011_auto_20200325_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
