# Generated by Django 3.0.4 on 2020-03-27 08:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0015_auto_20200325_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='msg',
            field=tinymce.models.HTMLField(),
        ),
    ]
