# Generated by Django 3.0.4 on 2020-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0016_auto_20200327_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='msg',
            field=models.TextField(),
        ),
    ]
