# Generated by Django 3.0.4 on 2020-03-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0017_auto_20200327_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
