# Generated by Django 3.0.4 on 2020-04-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0018_auto_20200328_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notif',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userreply',
            options={'ordering': ['created_at']},
        ),
    ]
