# Generated by Django 3.0.4 on 2020-04-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0019_auto_20200403_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenpostlike',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='givenreplylike',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
    ]
