# Generated by Django 3.0.4 on 2020-04-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0023_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='is_gamified',
            field=models.BooleanField(default=False),
        ),
    ]
