# Generated by Django 3.0.4 on 2020-04-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0025_auto_20200412_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='notif_type',
            field=models.CharField(choices=[('b', 'Badge'), ('g', 'Grade'), ('l', 'Like'), ('r', 'Reply'), ('p', 'Post'), (None, '-------')], default=None, max_length=1),
        ),
        migrations.CreateModel(
            name='PostNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_quantity', models.IntegerField()),
                ('notif', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sceleapp.Notif')),
            ],
        ),
    ]
