# Generated by Django 3.0.4 on 2020-04-14 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0028_replynotif_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replynotif',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sceleapp.UserReply'),
        ),
    ]
