# Generated by Django 3.0.4 on 2020-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0030_auto_20200416_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
