# Generated by Django 3.0.4 on 2020-04-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0032_auto_20200422_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
