# Generated by Django 3.0.4 on 2020-04-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sceleapp', '0034_notif_is_notifpage_opened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='is_notifpage_opened',
            new_name='is_notifpage_viewed',
        ),
    ]
